name: Build image and deploy to development server.

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@v2.5.0
        with:
          github-token: ${{ secrets.PACKAGE_TOKEN }}
          image-name: develop
          image-tag: 'last'
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Delete old docker and pull new docker
        uses: appleboy/ssh-action@master
        timeout-minutes: 15
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            docker pull ghcr.io/Nelie-Taylor/bot-sui/develop:last
            docker stop bot-sui
            docker rm bot-sui
            docker run -d --name bot-sui ghcr.io/Nelie-Taylor/bot-sui/develop:last
